name: Debug Check Run

on:
  check_run:
    types:
      - completed  # Listen for check completion
  workflow_dispatch:

jobs:
  debug-konflux:
    runs-on: ubuntu-latest

    steps:
      - name: Print Check Run Details
        run: |
          echo "Check Run Status: '${{ github.event.check_run.status }}'"
          echo "CI Check Name: '${{ github.event.check_run.name }}'"
          echo "Check Conclusion: '${{ github.event.check_run.conclusion }}'"
          echo "Check Run URL: '${{ github.event.check_run.html_url }}'"
          echo "Head Branch (if available): '${{ github.event.check_run.head_branch }}'"
          echo "Commit SHA: '${{ github.event.check_run.head_sha }}'"

      - name: Fetch Branch Name from Commit (Fallback)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # First, try to get the branch directly
          BRANCH_NAME="${{ github.event.check_run.head_branch }}"
          
          # If head_branch is empty, try fetching the branch using GitHub API
          if [[ -z "$BRANCH_NAME" ]]; then
            BRANCH_NAME=$(gh api repos/${{ github.repository }}/commits/${{ github.event.check_run.head_sha }}/branches-where-head --jq '.[0]')
          fi

          # If still empty, fetch all branches and find the one containing the commit
          if [[ -z "$BRANCH_NAME" ]]; then
            BRANCH_NAME=$(gh api repos/${{ github.repository }}/git/refs/heads --jq '[.[] | select(.object.sha == "${{ github.event.check_run.head_sha }}") | .ref] | map(sub("refs/heads/"; "")) | join(", ")')
          fi

          echo "Branch from commit: '$BRANCH_NAME'"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Check if Branch Matches `rhoai-*`
        if: startsWith(env.BRANCH_NAME, 'rhoai-')
        run: echo "This check run belongs to a rhoai-* branch!"
