name: Debug Check Run

on:
  check_run:
    types:
      - completed  # Listen for check completion
  workflow_dispatch:
  
jobs:
  debug-konflux:
    runs-on: ubuntu-latest

    steps:
      - name: Print Check Run Details
        run: |
          echo "Check Run Status: '${{ github.event.check_run.status }}'"
          echo "CI Check Name: '${{ github.event.check_run.name }}'"
          echo "Check Conclusion: '${{ github.event.check_run.conclusion }}'"
          echo "Check Run URL: '${{ github.event.check_run.html_url }}'"
          echo "Head Branch: '${{ github.event.check_run.head_branch }}'"

      - name: Check if Branch Matches `rhoai-*`
        if: startsWith(github.event.check_run.head_branch, 'rhoai-')
        run: echo "This check run belongs to a rhoai-* branch!"
